apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scadabr-uploads
  namespace: scada-minidash
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi


