apiVersion: v1
kind: Service
metadata:
  name: scadabr
  namespace: scada-minidash
spec:
  type: NodePort
  selector:
    app: scadabr
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080

