apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-backup-pvc
  namespace: scada-minidash
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn

