apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: mysql-pvc-usage
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
  - name: mysql-pvc.rules
    rules:
    - alert: MySQLPVCUsageHigh
      expr: |
        (
          kubelet_volume_stats_used_bytes{
            namespace="scada-minidash",
            persistentvolumeclaim="mysql-data-mysql-0"
          }
          /
          kubelet_volume_stats_capacity_bytes{
            namespace="scada-minidash",
            persistentvolumeclaim="mysql-data-mysql-0"
          }
        ) > 0.80
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "PVC do MySQL acima de 80%"
        description: "O PVC mysql-data-mysql-0 está acima de 80% de uso há mais de 5 minutos."

    - alert: MySQLPVCUsageCritical
      expr: |
        (
          kubelet_volume_stats_used_bytes{
            namespace="scada-minidash",
            persistentvolumeclaim="mysql-data-mysql-0"
          }
          /
          kubelet_volume_stats_capacity_bytes{
            namespace="scada-minidash",
            persistentvolumeclaim="mysql-data-mysql-0"
          }
        ) > 0.90
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "PVC do MySQL acima de 90%"
        description: "RISCO IMEDIATO: PVC mysql-data-mysql-0 acima de 90%. Ação urgente necessária."

