apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: scada-minidash
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      nodeSelector:
        role: scada-minidash

      securityContext:
        fsGroup: 999

      initContainers:
        - name: init-mysql-dir
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              mkdir -p /var/lib/mysql/data && \
              rm -rf /var/lib/mysql/data/* && \
              chown -R 999:999 /var/lib/mysql
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql

      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306

          securityContext:
            runAsUser: 999
            runAsGroup: 999

          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1"

          env:
            - name: MYSQL_DATABASE
              value: scadabr
            - name: MYSQL_USER
              value: scadabr
            - name: MYSQL_PASSWORD
              value: scadabr
            - name: MYSQL_ROOT_PASSWORD
              value: root

          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: mysql-config
              mountPath: /etc/mysql/conf.d

      volumes:
        - name: mysql-config
          configMap:
            name: mysql-config

  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi

